export const POINTS_PER_10_REAIS = 1;
export const VALUE_PER_POINT = 0.5;

export const LOYALTY_BOOKINGS_REQUIRED = 5;
export const LOYALTY_POINTS = 2;
export const BONUS_EXPIRATION_MONTHS = 6;

export const MIN_POINTS_TO_REDEEM = 10;
export const MIN_BOOKING_VALUE_AFTER_DISCOUNT = 0;

export const PASSWORD_HASH_ROUNDS = 6;
export const ACCESS_TOKEN_EXPIRATION_SECONDS = 60 * 60;
export const REFRESH_TOKEN_EXPIRATION_SECONDS = 60 * 60 * 24 * 7;
export const PASSWORD_RESET_TOKEN_EXPIRATION_HOURS = 2;
export const EMAIL_VERIFICATION_TOKEN_EXPIRATION_HOURS = 24;
export const SCHEDULE_SLOT_MINUTES = 15;
export const MAX_BOOKING_CANCEL_REASON_LENGTH = 255;
