/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Barber Shop
 * API para agendamento de serviços de barbearia
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * Criação de um novo feriado.
 */
export const createHolidayBodyNotesMax = 500;
export const createHolidayBodyUseBonusPointsDefault = false;export const createHolidayBodyCouponCodeMax = 50;


export const createHolidayBody = zod.object({
  "professionalId": zod.string().uuid(),
  "services": zod.array(zod.object({
  "serviceId": zod.string().uuid()
})),
  "startDateTime": zod.string().datetime({}),
  "notes": zod.string().max(createHolidayBodyNotesMax).optional(),
  "useBonusPoints": zod.boolean().optional(),
  "couponCode": zod.string().max(createHolidayBodyCouponCodeMax).optional()
})

/**
 * Listar feriados.
 */
export const listHolidaysQueryPageDefault = 1;
export const listHolidaysQueryPageMin = 0;
export const listHolidaysQueryLimitDefault = 10;
export const listHolidaysQueryLimitMin = 0;

export const listHolidaysQueryLimitMax = 100;


export const listHolidaysQueryParams = zod.object({
  "page": zod.number().min(listHolidaysQueryPageMin).default(listHolidaysQueryPageDefault),
  "limit": zod.number().min(listHolidaysQueryLimitMin).max(listHolidaysQueryLimitMax).default(listHolidaysQueryLimitDefault)
})

export const listHolidaysResponseTotalMin = 0;
export const listHolidaysResponsePageMin = 0;
export const listHolidaysResponseLimitMin = 0;
export const listHolidaysResponseTotalPagesMin = 0;


export const listHolidaysResponse = zod.object({
  "holidays": zod.array(zod.object({
  "id": zod.string().uuid(),
  "data": zod.string().datetime({}),
  "motivo": zod.string(),
  "profissionalId": zod.string().uuid()
})),
  "total": zod.number().min(listHolidaysResponseTotalMin),
  "page": zod.number().min(listHolidaysResponsePageMin),
  "limit": zod.number().min(listHolidaysResponseLimitMin),
  "totalPages": zod.number().min(listHolidaysResponseTotalPagesMin)
}).describe('Lista de feriados com paginação.')

/**
 * Deletar um feriado.
 */
export const deleteHolidayParams = zod.object({
  "holidayId": zod.string().uuid()
})

