services:
  barber-db:
    image: bitnami/postgresql:latest
    container_name: barber-db
    restart: always # Garante que o banco suba se cair
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    volumes:
      - barber_postgres_data:/bitnami/postgresql
    networks:
      - barber-network

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      # Filtragem de Spans de Baixo Valor (opcional - comentar para habilitar)
      # Remove spans de serialize, count e operações rápidas que geram "ruído"
      # - DD_APM_FILTER_TAGS_REJECT=["resource_name:serialize","resource_name:count"]
    ports:
      - '8126:8126'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      # Importante: o Agent precisa de acesso aos logs do Docker
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - barber-network


networks:
  barber-network:
    driver: bridge

volumes:
  barber_postgres_data: