/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Barber Shop
 * API para agendamento de serviços de barbearia
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * Atribuir bônus a um usuário.
 */
export const assignBonusToUserBody = zod.object({
  "userId": zod.string(),
  "bookingId": zod.string().optional(),
  "type": zod.enum(['BOOKING_POINTS', 'LOYALTY']),
  "description": zod.string().optional()
})

/**
 * Obter o saldo de bônus (pontos e valor em R$) do usuário autenticado.
 */
export const getBonusBalanceResponse = zod.object({
  "points": zod.object({
  "bookingPoints": zod.number(),
  "loyaltyPoints": zod.number(),
  "totalPoints": zod.number()
}),
  "monetaryValue": zod.object({
  "bookingValue": zod.number(),
  "loyaltyValue": zod.number(),
  "totalValue": zod.number()
})
})

