/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Barber Shop
 * API para agendamento de serviços de barbearia
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * Registro de novo usuário.
 */
export const registerUserBodyNomeMin = 3;
export const registerUserBodySenhaMin = 6;


export const registerUserBody = zod.object({
  "nome": zod.string().min(registerUserBodyNomeMin),
  "email": zod.string().email(),
  "senha": zod.string().min(registerUserBodySenhaMin),
  "role": zod.enum(['CLIENTE', 'PROFISSIONAL', 'ADMIN']).optional()
})

/**
 * Autenticação do usuário.
 */
export const loginUserBodySenhaMin = 6;


export const loginUserBody = zod.object({
  "email": zod.string().email(),
  "senha": zod.string().min(loginUserBodySenhaMin)
})

export const loginUserResponse = zod.object({
  "token": zod.string(),
  "user": zod.object({
  "id": zod.string().uuid(),
  "nome": zod.string(),
  "email": zod.string().email().optional(),
  "telefone": zod.string().nullish(),
  "role": zod.enum(['CLIENTE', 'PROFISSIONAL', 'ADMIN']).optional(),
  "emailVerified": zod.boolean(),
  "active": zod.boolean(),
  "createdAt": zod.string().datetime({})
})
}).describe('Login bem-sucedido')

/**
 * Logout do usuário, removendo cookies de autenticação.
 */
export const logoutUserResponse = zod.object({
  "message": zod.string()
}).describe('Logout realizado com sucesso.')

/**
 * Geração de um novo token de acesso com base no refresh token válido presente nos cookies.
 */
export const refreshTokenResponse = zod.object({
  "token": zod.string()
}).describe('Novo token gerado com sucesso.')

