/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API Barber Shop
 * API para agendamento de serviços de barbearia
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';


/**
 * Criação de um novo horário de funcionamento.
 */
export const createBusinessHourBodyDiaSemanaMin = 0;

export const createBusinessHourBodyDiaSemanaMax = 6;
export const createBusinessHourBodyAbreAsRegExp = new RegExp('^([01]?[0-9]|2[0-3]):[0-5][0-9]$');
export const createBusinessHourBodyFechaAsRegExp = new RegExp('^([01]?[0-9]|2[0-3]):[0-5][0-9]$');
export const createBusinessHourBodyPausaInicioRegExp = new RegExp('^([01]?[0-9]|2[0-3]):[0-5][0-9]$');
export const createBusinessHourBodyPausaFimRegExp = new RegExp('^([01]?[0-9]|2[0-3]):[0-5][0-9]$');


export const createBusinessHourBody = zod.object({
  "professionalId": zod.string(),
  "diaSemana": zod.number().min(createBusinessHourBodyDiaSemanaMin).max(createBusinessHourBodyDiaSemanaMax),
  "abreAs": zod.string().regex(createBusinessHourBodyAbreAsRegExp),
  "fechaAs": zod.string().regex(createBusinessHourBodyFechaAsRegExp),
  "pausaInicio": zod.string().regex(createBusinessHourBodyPausaInicioRegExp).nullish(),
  "pausaFim": zod.string().regex(createBusinessHourBodyPausaFimRegExp).nullish()
})

/**
 * Atualização de um horário de funcionamento.
 */
export const updateBusinessHourParams = zod.object({
  "professionalId": zod.string()
})

export const updateBusinessHourBodyDiaSemanaMin = 0;

export const updateBusinessHourBodyDiaSemanaMax = 6;


export const updateBusinessHourBody = zod.object({
  "diaSemana": zod.number().min(updateBusinessHourBodyDiaSemanaMin).max(updateBusinessHourBodyDiaSemanaMax),
  "abreAs": zod.string().optional(),
  "fechaAs": zod.string().optional(),
  "pausaInicio": zod.string().nullish(),
  "pausaFim": zod.string().nullish()
})

export const updateBusinessHourResponse = zod.enum(['null']).nullable().describe('Horário de funcionamento atualizado com sucesso.')

/**
 * Listar horários de funcionamento.
 */
export const listBusinessHoursParams = zod.object({
  "professionalId": zod.string().uuid()
})

export const listBusinessHoursResponseBusinessHoursItemDiaSemanaMin = 0;

export const listBusinessHoursResponseBusinessHoursItemDiaSemanaMax = 6;


export const listBusinessHoursResponse = zod.object({
  "businessHours": zod.array(zod.object({
  "id": zod.string().uuid(),
  "ativo": zod.boolean(),
  "diaSemana": zod.number().min(listBusinessHoursResponseBusinessHoursItemDiaSemanaMin).max(listBusinessHoursResponseBusinessHoursItemDiaSemanaMax),
  "abreAs": zod.string(),
  "fechaAs": zod.string(),
  "pausaInicio": zod.string().nullable(),
  "pausaFim": zod.string().nullable(),
  "profissionalId": zod.string()
}))
}).describe('Horários de funcionamento encontrados.')

/**
 * Deletar um horário de funcionamento.
 */
export const deleteBusinessHourParams = zod.object({
  "businessHoursId": zod.string().uuid()
})

